name: Build Lua
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-lua.yml'

jobs:
  build-lua:
    name: Build Lua in Steam Runtime
    runs-on: ubuntu-latest
    env:
      LUA_VERSION: 5.4.6
    steps:
      - name: Build in Steam Runtime container
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: -v ${{ github.workspace }}:/work
          run: |
            apt-get update
            apt-get install -y curl build-essential
            cd /tmp
            curl -L "https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz" -o lua.tar.gz
            tar xzf lua.tar.gz
            cd "lua-${LUA_VERSION}"
            make MYCFLAGS=-fPIC MYLDFLAGS=-shared linux
            mkdir -p /work/artifacts
            cp src/liblua.so /work/artifacts/liblua5.4.so

      - name: Upload Lua library
        uses: actions/upload-artifact@v4
        with:
          name: steamrt-lua
          path: artifacts/liblua5.4.so
          if-no-files-found: error
