name: Build Rust Library
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-rust.yml'
      - 'lib/**'

jobs:
  build-rust:
    name: Build Rust in Steam Runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build in Steam Runtime container
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: -v ${{ github.workspace }}:/work
          run: |
            set -ex

            # Debug system info
            echo "System information:"
            uname -a
            ldd --version
            cat /etc/issue || true

            # Check available GCC versions
            ls -la /usr/bin/gcc*
            gcc-9 --version

            apt-get update
            apt-get install -y curl build-essential gcc-9 g++-9 wget

            # Try to install Rust using the official package instead of rustup
            echo "Attempting to install Rust from packaged version..."
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" > /etc/apt/sources.list.d/llvm.list
            apt-get update
            apt-get install -y rustc cargo

            # Debug Rust installation
            echo "Rust version:"
            rustc --version
            cargo --version

            # Create linker script inside container
            cat > /tmp/linker.sh << 'EOL'
            #!/bin/bash
            echo "Linker args: $@" >&2
            for arg do
              shift
              case $arg in
                (-lgcc_s) : ;;
                   (*) set -- "$@" "$arg" ;;
              esac
            done
            echo "Modified linker args: $@" >&2
            exec "$CC" "$@" -lgcc
            EOL
            chmod +x /tmp/linker.sh

            # Setup modern GCC with debug output
            export CC=gcc-9
            export CXX=g++-9
            echo "CC version: $($CC --version)"

            # Configure Rust to use our linker script with verbose output
            export RUSTFLAGS="-C linker=/tmp/linker.sh -C link-arg=-v"

            cd /work/lib
            # Build with more verbose output
            RUST_BACKTRACE=1 cargo build -vv --release

            mkdir -p /work/artifacts
            cp target/release/libdmi.so /work/artifacts/

      - name: Upload Rust library
        uses: actions/upload-artifact@v4
        with:
          name: steamrt-rust
          path: artifacts/libdmi.so
          if-no-files-found: error
