name: Build Lua
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-lua.yml'

jobs:
  build-lua:
    name: Build Lua in Steam Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Build in Steam Runtime container
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: -v ${{ github.workspace }}:/work
          run: |
            # start
            set -ex
            apt-get update
            apt-get install -y curl build-essential

            WORKDIR="/tmp/lua-build"
            mkdir -p "$WORKDIR"
            cd "$WORKDIR"

            # Download with proper error checking
            curl -fsSL "https://www.lua.org/ftp/lua-5.4.7.tar.gz" --output lua.tar.gz

            # Verify download
            if [ ! -s lua.tar.gz ]; then
              echo "Download failed or file is empty"
              exit 1
            fi

            # Extract with verification
            tar xf lua.tar.gz
            if [ ! -d "lua-5.4.7" ]; then
              echo "Extraction failed"
              exit 1
            fi

            cd "lua-5.4.7"

            # Download and apply patch
            curl -fsSL "https://gist.githubusercontent.com/ZeWaka/5d8a24ded388763bfd2e5213093eac95/raw/63d7664347bbdd59389a8af6eeeb5531335af35c/liblua.so.patch" -o lua-shared-lib.patch
            patch -p1 < lua-shared-lib.patch

            # Build with patched Makefile and PIC
            make linux MYCFLAGS="-fPIC"

            cd src

            # Test the library
            nm -D liblua.so | grep ' T ' || echo "No exported symbols found!"
            ldd liblua.so || echo "Library dependencies not found!"

            # Copy and rename
            mkdir -p /work/artifacts
            cp liblua.so /work/artifacts/liblua5.4.so

            # Verify copy
            if [ ! -f /work/artifacts/liblua5.4.so ]; then
              echo "Failed to copy library"
              exit 1
            fi

      - name: Upload Lua library
        uses: actions/upload-artifact@v4
        with:
          name: steamrt-lua
          path: artifacts/liblua5.4.so
          if-no-files-found: error
