name: Build Lua
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-lua.yml'

jobs:
  build-lua:
    name: Build Lua in Steam Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Build in Steam Runtime container
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: -v ${{ github.workspace }}:/work
          run: |
            # start
            set -ex
            apt-get update
            apt-get install -y curl build-essential

            WORKDIR="/tmp/lua-build"
            mkdir -p "$WORKDIR"
            cd "$WORKDIR"

            # Download with proper error checking
            curl -fsSL "https://www.lua.org/ftp/lua-5.4.6.tar.gz" --output lua.tar.gz

            # Verify download
            if [ ! -s lua.tar.gz ]; then
              echo "Download failed or file is empty"
              exit 1
            fi

            # Extract with verification
            tar xf lua.tar.gz
            if [ ! -d "lua-5.4.6" ]; then
              echo "Extraction failed"
              exit 1
            fi

            cd "lua-5.4.6"

            # Create custom config
            cat > src/luaconf.h.new << 'EOF'
            #include "luaconf.h"
            #undef LUAI_FUNC
            #undef LUAI_DDEC
            #undef LUAI_DDEF
            #define LUAI_FUNC extern
            #define LUAI_DDEC(def) def
            #define LUAI_DDEF(def) def
            EOF

            # Backup original and replace with our version
            mv src/luaconf.h src/luaconf.h.orig
            mv src/luaconf.h.new src/luaconf.h

            # Modify Makefile for shared library
            sed -i 's/MYCFLAGS=/MYCFLAGS=-fPIC /' src/Makefile
            sed -i 's/MYLDFLAGS=/MYLDFLAGS=-shared /' src/Makefile
            sed -i 's/ALL_T=/ALL_T= $(LUA_SO)/' src/Makefile
            sed -i 's/TO_BIN= lua luac/TO_BIN= liblua5.4.so/' src/Makefile

            # Build
            make linux

            # Verify and copy
            cd src
            if [ ! -f liblua5.4.so ]; then
              echo "Build failed - library not found"
              exit 1
            fi

            # Test the library
            nm -D liblua5.4.so | grep ' T ' || echo "No exported symbols found!"
            ldd liblua5.4.so || echo "Library dependencies not found!"

            mkdir -p /work/artifacts
            cp liblua5.4.so /work/artifacts/

            # Verify copy
            if [ ! -f /work/artifacts/liblua5.4.so ]; then
              echo "Failed to copy library"
              exit 1
            fi

      - name: Upload Lua library
        uses: actions/upload-artifact@v4
        with:
          name: steamrt-lua
          path: artifacts/liblua5.4.so
          if-no-files-found: error
